# Generated by Django 5.2 on 2025-04-24 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_projectmembership_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmembership',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('DEVELOPER', 'Developer'), ('TESTER', 'Tester'), ('DESIGNER', 'Designer'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
